name: 'test_and_benchmark'
on: push
jobs:
  test-and-benchmark:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13.12'
        - name: Build CMake
          run: |
            mkdir build
            cmake -B build -DCMAKE_BUILD_TYPE=RELEASE
            cmake --build build
        - name: Check all tests valid
          run: |
            python3 scripts/check_all_tests_valid.py
        - name: Run benchmark tests
          run: |
            python3 scripts/run_benchmark_tests.py
        - name: Verify changed files
          uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf
          id: verify-changed-files
          with:
            files: benchmark_results
        - name: Commit files
          if: steps.verify-changed-files.outputs.files_changed == 'true'
          run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add benchmark_results
            git commit -m "Updated benchmark_results"
        - name: Push changes
          if: steps.verify-changed-files.outputs.files_changed == 'true'
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.github_token }}
            branch: ${{ github.ref }}